name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 16.171.64.218
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/digital_library_showcase"

      - name: Deploy with Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 16.171.64.218
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/digital_library_showcase

            sudo docker stop $(sudo docker ps -q) || true
            sudo docker rm $(sudo docker ps -aq) || true

            sudo docker build -t digital-library .
            sudo docker run -d -p 80:80 digital-library